name: "Intellizzer"
description: "An intelligent GitHub Action that enhances code reviews with advanced language models and pull request recommendations."

inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true

  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true

  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "gpt-4o"

  OPENAI_API_ENDPOINT:
    description: "Custom OpenAI API endpoint URL (optional)"
    required: false

  TELEGRAM_BOT_TOKEN:
    description: "Telegram Bot Token for notifications"
    required: true

  TELEGRAM_CHAT_ID:
    description: "Telegram Chat ID to send notifications"
    required: true

  ENABLE_TELEGRAM_BOT:
    description: "Enable Telegram bot functionality"
    required: false
    default: 'false'

  BOT_NAME:
    description: "Name of the bot that will appear in comments"
    required: false
    default: "Code Review Bot"

  exclude:
    description: "Glob patterns to exclude files from the diff analysis (comma-separated)"
    required: false
    default: "*.md,*.txt,package-lock.json,yarn.lock"

runs:
  using: "node20" # Updated to use Node.js 20
  main: "dist/index.js"

branding:
  icon: "cpu"
  color: "red"
author: 'Blizzer'
